/*------------------------------------------------------------------------------------------------------------------
-- SOURCE FILE: 		main.cpp - An application that allows the user to interface with the transpor layer.
--
-- PROGRAM: 			TransportLayerAnalyser
--
-- FUNCTIONS:			int main(int argc, char * argv[])
--
-- DATE: 				Feb 5, 2018
--
-- DESIGNER: 			Qt
--
-- PROGRAMMER: 			Qt
--
-- NOTES:
-- This file only contains the default code that is generated by Qt.
----------------------------------------------------------------------------------------------------------------------*/
#include "TransportLayerAnalyser.h"
#include <QtWidgets/QApplication>

/*------------------------------------------------------------------------------------------------------------------
-- FUNCTION: 			main
--
-- DATE: 				Feb 5, 2018
--
-- DESIGNER: 			Benny Wang
--
-- PROGRAMMER: 			Benny Wang
--
-- INTERFACE: 			int main (int argc, char * argv[])
--							int argc: The amount of commandline arguements passed to the program. Not used.
--							char * argv[]: List of command line arguements passed to the program. Not used.
--
-- RETURNS: 			An exit code.
--
-- NOTES:
-- This is the entry point of the program. All the code here is auto-generated for a Qt GUI application. The first lines
-- of code that are executed after this can be found in the constructor of TransportLayerAnalyser.
----------------------------------------------------------------------------------------------------------------------*/
int main(int argc, char *argv[])
{
	QApplication a(argc, argv);
	TransportLayerAnalyser w;
	w.show();
	return a.exec();
}
